//! The `#[derive(ViewModel)]` implementation.
//!
//! Generates, from an authored POD struct `Foo`:
//!
//! * a `#[repr(C)]`, `Copy` image struct `FooImage` with every C-like enum
//!   field lowered to its `ImageEnum::Repr` backing integer (seqlock-safe);
//! * `to_image` / `from_image` (which round-trip for all in-range values);
//! * `schema()`, `IMAGE_SIZE`, `MAX_ENCODED_SIZE`, and `image_to_json`.

use proc_macro2::{Span, TokenStream};
use quote::quote;
use syn::{Data, DeriveInput, Fields};

use crate::layout::{
    self, field_type_expr, from_image_expr, image_field_type, json_budget_term, to_image_expr,
};

pub fn derive(input: TokenStream) -> syn::Result<TokenStream> {
    let ast: DeriveInput = syn::parse2(input)?;
    let ident = &ast.ident;
    let name_str = ident.to_string();
    let krate = layout::krate();

    if !ast.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &ast.generics,
            "ViewModel does not support generic, lifetime, or const-generic structs",
        ));
    }
    layout::reject_serde_rename(&ast.attrs)?;

    let Data::Struct(data) = &ast.data else {
        return Err(syn::Error::new_spanned(
            ident,
            "ViewModel can only be derived for structs",
        ));
    };
    let Fields::Named(named) = &data.fields else {
        return Err(syn::Error::new_spanned(
            ident,
            "ViewModel requires named fields",
        ));
    };

    let image_ident = syn::Ident::new(&format!("{ident}Image"), Span::call_site());

    let mut image_fields = Vec::new();
    let mut to_image = Vec::new();
    let mut from_image = Vec::new();
    let mut schema_fields = Vec::new();
    let mut budget_terms = Vec::new();

    for field in &named.named {
        layout::reject_serde_rename(&field.attrs)?;
        let fident = field.ident.as_ref().expect("named field");
        let fname = fident.to_string();
        let kind = layout::classify(&field.ty)?;
        let field_tokens = quote!(#fident);

        let img_ty = image_field_type(&kind, &field.ty);
        image_fields.push(quote!(pub #fident: #img_ty));

        let to_e = to_image_expr(&kind, &field_tokens);
        to_image.push(quote!(#fident: #to_e));

        let from_e = from_image_expr(&kind, &field_tokens);
        from_image.push(quote!(#fident: #from_e));

        let ft = field_type_expr(&kind);
        schema_fields.push(quote! {
            #krate::contract::FieldSchema {
                name: #fname.to_owned(),
                ty: #ft,
            }
        });

        budget_terms.push(json_budget_term(&kind, &fname));
    }

    let expanded = quote! {
        /// Integer-lowered `#[repr(C)]` image generated by `#[derive(ViewModel)]`.
        #[doc(hidden)]
        #[repr(C)]
        #[derive(::std::clone::Clone, ::std::marker::Copy)]
        pub struct #image_ident {
            #( #image_fields, )*
        }

        impl #krate::ViewModel for #ident {
            type Image = #image_ident;

            const IMAGE_SIZE: usize = ::std::mem::size_of::<#image_ident>();

            const MAX_ENCODED_SIZE: usize = 2usize #( + #budget_terms )*;

            fn schema() -> #krate::contract::ViewModelSchema {
                #krate::contract::ViewModelSchema {
                    name: #name_str.to_owned(),
                    service: ::std::string::String::new(),
                    fields: ::std::vec![ #( #schema_fields, )* ],
                }
            }

            fn to_image(&self) -> Self::Image {
                #image_ident {
                    #( #to_image, )*
                }
            }

            fn from_image(image: &Self::Image) -> Self {
                Self {
                    #( #from_image, )*
                }
            }

            fn image_to_json(image: &Self::Image, buf: &mut ::std::vec::Vec<u8>) {
                let __vm = <Self as #krate::ViewModel>::from_image(image);
                #krate::__private::serde_json::to_writer(buf, &__vm)
                    .expect("ViewModel JSON serialization is infallible for POD");
            }
        }
    };

    Ok(expanded)
}
