//! Domain-facing EL7047 control/status types and process-image lengths for the
//! `ethercat-stepper` example. These are decoupled from the wire codec, which
//! is now fully generated by the ESI codegen toolchain. The generated codec
//! lives in [`crate::generated`]; the mapping between these domain types and
//! the generated device is in [`crate::el7047_adapter`].

/// Output (RxPDO) process image length for the positioning-interface assignment.
/// Used as a const-generic array size in `main.rs` for the EL7047 output channel.
pub const OUTPUT_LEN: usize = 22;
/// Input (TxPDO) process image length for the positioning-interface assignment.
/// Used as a const-generic array size in `main.rs` for the EL7047 input channel.
pub const INPUT_LEN: usize = 24;

/// Beckhoff POS "Start type" values (from the ESI DT0808EN16 enum).
pub mod start_type {
    /// Relative move: the target position is a delta from the current one.
    pub const RELATIVE: u16 = 2;
    /// Endless move in the positive direction (jog) — runs while Execute is held
    /// and stops when it drops or the drive stalls. Target position is ignored.
    pub const ENDLESS_PLUS: u16 = 3;
    /// Endless move in the negative direction (jog).
    pub const ENDLESS_MINUS: u16 = 4;
}

/// Decoded EL7047 status (subset we care about).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct El7047Status {
    /// STM Status bit1: drive is enabled and ready to move.
    pub ready: bool,
    /// STM Status bit3: drive fault latched.
    pub error: bool,
    /// STM Status bit2: non-fatal warning active.
    pub warning: bool,
    /// STM Status bit7: motor stall detected.
    pub motor_stall: bool,
    /// POS Status bit0: a positioning move is in progress.
    pub busy: bool,
    /// POS Status bit1: the commanded position has been reached.
    pub in_target: bool,
    /// POS Status bit7: ready to accept a new Execute pulse.
    pub ready_to_execute: bool,
    /// Actual position counter (increments).
    pub actual_position: i32,
}

/// Control surface we write each cycle.
#[derive(Clone, Copy, Debug, Default)]
pub struct El7047Control {
    /// STM Control bit0: enable the drive.
    pub enable: bool,
    /// STM Control bit1: reset a latched fault.
    pub reset: bool,
    /// POS Control bit0: pulse to start the configured move.
    pub execute: bool,
    /// POS Control bit1: emergency-stop the drive.
    pub emergency_stop: bool,
    /// Target position (delta when `start_type` is Relative).
    pub target_position: i32,
    /// Move velocity (POS-interface raw units).
    pub velocity: i16,
    /// Start-type selector (see [`start_type`]).
    pub start_type: u16,
    /// Acceleration ramp (POS-interface raw units).
    pub acceleration: u16,
    /// Deceleration ramp (POS-interface raw units).
    pub deceleration: u16,
    /// ENC Control bit2 ("Set counter"): pulse to load `set_counter_value`
    /// into the position counter (manual zero / datum).
    pub set_counter: bool,
    /// ENC "Set counter value" — the value loaded when `set_counter` pulses.
    pub set_counter_value: i32,
}
